-- Placeholder migration for remote version 0001
-- Solo existe para alinear el historial local/remoto de Supabase.
-- NO BORRAR sin actualizar antes el historial de supabase_migrations.schema_migrations.
