-- 0009_auth_logs.sql

create table if not exists public.auth_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event text not null check (event in ('login','logout')),
  ip text,
  user_agent text,
  created_at timestamptz default now()
);

create index if not exists idx_auth_logs_user_created_at
  on public.auth_logs(user_id, created_at desc);

